spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    pool_mode: transaction
    hikari:
      maximum-pool-size: 5    # 최대 풀 사이즈 (DB 리밋보다 작게)
      minimum-idle: 2
      idle-timeout: 30000      # 30초
      max-lifetime: 600000     # 10분
      connection-timeout: 30000
      leak-detection-threshold: 2000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
  batch:
    job:
      enable: false

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging.level:
  root: INFO
  org.hibernate.SQL: DEBUG
  org.hibernate.orm.jdbc.bind: DEBUG
  org.springframework.session.data.redis: debug

server:
  port: 8080
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

batch:
  enabled: true

springdoc:
  swagger-ui:
    path: /api/docs
    operationsSorter: method
    tagsSorter: alpha

  use-fqn: true
