name: 'Build and Deploy'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGION: 'asia-northeast3'
  SERVICE: 'suclan-back'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        run: |
          cd suclan
          docker build . -t suclan-back:${{ github.ref_name }} -f Dockerfile --no-cache --push --build-arg DB_USER=${{ secrets.DB_USER }} --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Set output
        id: set_output
        run: echo "image_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT

  deploy-cloudrun:
    needs: build
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name below:
          image: suclan-back:${{ github.ref_name }}
      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}